# Generated by Django 5.2.3 on 2025-10-01 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payer_type',
            field=models.CharField(choices=[('single', 'Single Payer'), ('multiple', 'Multiple Payers')], default='single', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.groupmember'),
        ),
        migrations.CreateModel(
            name='ExpensePayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payers', to='expenses.expense')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.groupmember')),
            ],
        ),
    ]
